# Generated by Django for code-owned document branding.

from django.db import migrations


CANONICAL_VALUES = {
    "country_line": "Republic of the Philippines",
    "institution_name": "University of Camarines Norte",
    "institution_short_name": "UCN",
    "former_institution_name": "Camarines Norte State College",
    "institution_address": None,
    "institution_website_url": None,
    "institution_contact_email": None,
    "institution_social_url": None,
    "office_parent_unit_name": None,
    "office_name": "Guidance and Counseling Office",
    "office_email": None,
    "office_phone": None,
    "office_location": None,
}


def refuse_divergent_branding_removal(apps, schema_editor):
    """Fail closed before dropping persisted branding that differs from code-owned facts."""

    profile_model = apps.get_model("documents", "DocumentBrandingProfile")
    alias = schema_editor.connection.alias
    for profile in profile_model.objects.using(alias).all():
        differing_fields = [
            field_name
            for field_name, canonical_value in CANONICAL_VALUES.items()
            if getattr(profile, field_name) != canonical_value
        ]
        if differing_fields:
            fields = ", ".join(sorted(differing_fields))
            raise RuntimeError(
                "Document Branding removal stopped because persisted branding differs from "
                f"the code-owned definition for profile {profile.key!r}; differing fields: {fields}. "
                "Update the canonical source definition deliberately before retrying this migration."
            )


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            refuse_divergent_branding_removal,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.DeleteModel(
            name="DocumentBrandingProfile",
        ),
    ]
