# Generated by Django 6.1.1 on 2026-09-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='audience',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('ALL_AUTHENTICATED', 'All authenticated'), ('STUDENTS', 'Students'), ('GCO_PERSONNEL', 'GCO personnel')], max_length=32),
        ),
    ]
