# Generated by Django 6.1.1 on 2026-10-10 05:03

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name', 'id'),
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='assessment_type_name_unique'), models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='assessment_type_name_nonblank')],
            },
        ),
        migrations.CreateModel(
            name='StudentAssessmentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('administered_on', models.DateField()),
                ('confidential_content_ciphertext', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='assessment_records.assessmenttype')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_assessment_records', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-administered_on', 'id'),
                'default_permissions': (),
                'indexes': [models.Index(fields=['student', '-administered_on'], name='assessment__student_2adf6a_idx'), models.Index(fields=['assessment_type', '-administered_on'], name='assessment__assessm_bd1ad8_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('confidential_content_ciphertext', ''), _negated=True), name='assessment_record_ciphertext_nonblank')],
            },
        ),
    ]
