# Generated by Django 6.1.1 on 2026-09-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0002_service_cancellation_cutoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='requires_current_inventory',
            field=models.BooleanField(default=False),
        ),
    ]
