# Generated by Django 5.2.6 on 2026-09-19

from django.db import migrations, models
from django.db.models import F, Q


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MaintenanceConfiguration",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("manual_enabled", models.BooleanField(default=False)),
                (
                    "manual_message",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("manual_expected_end_at", models.DateTimeField(blank=True, null=True)),
                ("scheduled_start_at", models.DateTimeField(blank=True, null=True)),
                ("scheduled_end_at", models.DateTimeField(blank=True, null=True)),
                (
                    "scheduled_message",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "default_permissions": (),
                "constraints": [
                    models.CheckConstraint(
                        condition=Q(("id", 1)),
                        name="platform_maint_singleton_pk",
                    ),
                    models.CheckConstraint(
                        condition=(
                            Q(
                                ("scheduled_end_at__isnull", True),
                                ("scheduled_start_at__isnull", True),
                            )
                            | Q(
                                ("scheduled_end_at__gt", F("scheduled_start_at")),
                                ("scheduled_end_at__isnull", False),
                                ("scheduled_start_at__isnull", False),
                            )
                        ),
                        name="platform_maint_schedule_pair",
                    ),
                ],
            },
        ),
    ]
