# Generated by Django 5.2 for the E-Counseling Daily foundation.

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ECounselingRoom",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("daily_room_name", models.CharField(max_length=128, unique=True)),
                ("daily_room_id", models.CharField(blank=True, max_length=128, null=True)),
                ("daily_room_url", models.URLField(blank=True, max_length=500, null=True)),
                ("room_expires_at", models.DateTimeField(blank=True, null=True)),
                ("provisioned_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ecounseling_room",
                        to="appointments.appointment",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="DailyWebhookReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("provider_event_id", models.CharField(max_length=160, unique=True)),
                ("event_type", models.CharField(max_length=80)),
                ("provider_session_id", models.CharField(blank=True, max_length=160, null=True)),
                ("provider_occurred_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ecounseling_room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_webhook_receipts",
                        to="ecounseling.ecounselingroom",
                    ),
                ),
            ],
            options={
                "ordering": ("-received_at", "id"),
                "default_permissions": (),
                "indexes": [
                    models.Index(fields=["event_type", "-received_at"], name="daily_event_time_idx")
                ],
            },
        ),
    ]
