# Generated by Django 5.2 for the E-Counseling media consent foundation.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("ecounseling", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ECounselingConsent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("AUDIO_VIDEO_RECORDING", "Audio/video recording"),
                            ("LIVE_TRANSCRIPTION", "Live transcription"),
                            ("TRANSCRIPT_STORAGE", "Transcript storage"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("DENIED", "Denied"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consents",
                        to="ecounseling.ecounselingroom",
                    ),
                ),
            ],
            options={
                "ordering": ("requested_at", "id"),
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="ECounselingMediaCapture",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("RECORDING", "Recording"),
                            ("TRANSCRIPTION", "Transcription"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not started"),
                            ("START_REQUESTED", "Start requested"),
                            ("ACTIVE", "Active"),
                            ("STOP_REQUESTED", "Stop requested"),
                            ("STOPPED", "Stopped"),
                            ("READY", "Ready"),
                            ("ERROR", "Error"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                ("transcript_storage_enabled", models.BooleanField(default=False)),
                ("provider_instance_id", models.CharField(blank=True, max_length=160, null=True)),
                ("provider_artifact_id", models.CharField(blank=True, max_length=160, null=True)),
                ("provider_session_id", models.CharField(blank=True, max_length=160, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("stop_requested_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("ready_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=80, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="media_captures",
                        to="ecounseling.ecounselingroom",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
                "default_permissions": (),
            },
        ),
        migrations.AddConstraint(
            model_name="ecounselingconsent",
            constraint=models.UniqueConstraint(
                fields=("room", "scope"),
                name="ec_consent_room_scope_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="ecounselingconsent",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        ("decision", "PENDING"),
                        ("decided_at__isnull", True),
                        ("withdrawn_at__isnull", True),
                    )
                    | models.Q(
                        ("decision__in", ("APPROVED", "DENIED")),
                        ("decided_at__isnull", False),
                    )
                ),
                name="ec_consent_decision_time_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="ecounselingconsent",
            constraint=models.CheckConstraint(
                condition=models.Q(("withdrawn_at__isnull", True))
                | models.Q(("decision", "APPROVED")),
                name="ec_consent_withdrawn_approved_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="ecounselingmediacapture",
            constraint=models.UniqueConstraint(
                fields=("room", "kind"),
                name="ec_media_room_kind_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="ecounselingmediacapture",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind", "TRANSCRIPTION"))
                | models.Q(("transcript_storage_enabled", False)),
                name="ec_media_storage_transcription_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="ecounselingmediacapture",
            constraint=models.CheckConstraint(
                condition=models.Q(("duration_seconds__isnull", True))
                | models.Q(("duration_seconds__gte", 0)),
                name="ec_media_duration_nonnegative_ck",
            ),
        ),
    ]
