# Generated by Django 6.1.1 on 2026-10-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecounseling', '0002_consent_media_capture'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecounselingmediacapture',
            name='artifact_disposed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
