# Generated by Django 6.1.1 on 2026-10-07 22:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_service_name_snapshot'),
        ('ecounseling', '0003_ecounselingmediacapture_artifact_disposed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECounselingMediaArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('STORED', 'Stored'), ('FAILED', 'Failed'), ('DISPOSED', 'Disposed')], default='PENDING', max_length=16)),
                ('object_key', models.CharField(max_length=180, null=True)),
                ('content_type', models.CharField(max_length=80, null=True)),
                ('size', models.PositiveBigIntegerField(null=True)),
                ('sha256', models.CharField(max_length=64, null=True)),
                ('stored_at', models.DateTimeField(null=True)),
                ('disposed_at', models.DateTimeField(null=True)),
                ('provider_deleted_at', models.DateTimeField(null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('claim_token', models.UUIDField(null=True)),
                ('claimed_at', models.DateTimeField(null=True)),
                ('next_attempt_at', models.DateTimeField(null=True)),
                ('error_code', models.CharField(max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='ecounselingmediacapture',
            name='media_authorized_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ecounselingmediacapture',
            name='transcript_storage_authorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ecounselingroom',
            name='media_policy_version',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Legacy granular consent'), (2, 'Media policy v2')], default=1),
        ),
        # Existing bindings remain V1. Altering the application default creates no new evidence.
        migrations.AlterField(
            model_name='ecounselingroom',
            name='media_policy_version',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Legacy granular consent'), (2, 'Media policy v2')], default=2),
        ),
        migrations.AlterField(
            model_name='ecounselingconsent',
            name='scope',
            field=models.CharField(choices=[('SESSION_MEDIA_CAPTURE', 'Recording and live transcription'), ('AUDIO_VIDEO_RECORDING', 'Audio/video recording'), ('LIVE_TRANSCRIPTION', 'Live transcription'), ('TRANSCRIPT_STORAGE', 'Transcript storage')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='ecounselingroom',
            constraint=models.CheckConstraint(condition=models.Q(('media_policy_version__in', [1, 2])), name='ec_room_media_policy_valid'),
        ),
        migrations.AddField(
            model_name='ecounselingmediaartifact',
            name='capture',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='artifact', to='ecounseling.ecounselingmediacapture'),
        ),
        migrations.AddIndex(
            model_name='ecounselingmediaartifact',
            index=models.Index(fields=['status', 'next_attempt_at'], name='ec_artifact_dispatch_idx'),
        ),
        migrations.AddConstraint(
            model_name='ecounselingmediaartifact',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'PROCESSING', 'STORED', 'FAILED', 'DISPOSED'])), name='ec_artifact_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='ecounselingmediaartifact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'STORED'), _negated=True), models.Q(('content_type__isnull', False), ('disposed_at__isnull', True), ('object_key__isnull', False), ('sha256__isnull', False), ('size__gt', 0), ('size__isnull', False), ('stored_at__isnull', False)), _connector='OR'), name='ec_artifact_stored_shape'),
        ),
        migrations.AddConstraint(
            model_name='ecounselingmediaartifact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'DISPOSED'), _negated=True), models.Q(('disposed_at__isnull', False), ('object_key__isnull', True), ('sha256__isnull', True)), _connector='OR'), name='ec_artifact_disposed_shape'),
        ),
    ]
