# Generated by Django 5.2.6 on 2026-09-19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivacyIncident",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("reference_code", models.CharField(editable=False, max_length=32, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField(max_length=3000)),
                ("affected_area", models.CharField(max_length=255)),
                ("personal_data_categories", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("ASSESSING", "Assessing"),
                            ("CONTAINED", "Contained"),
                            ("RESOLVED", "Resolved"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("occurred_at", models.DateTimeField(blank=True, null=True)),
                ("discovered_at", models.DateTimeField()),
                ("estimated_affected_subjects", models.PositiveIntegerField(blank=True, null=True)),
                ("assessment_summary", models.TextField(blank=True, default="", max_length=4000)),
                ("containment_summary", models.TextField(blank=True, default="", max_length=4000)),
                (
                    "notification_assessment",
                    models.CharField(
                        choices=[
                            ("NOT_ASSESSED", "Not assessed"),
                            ("NOT_REQUIRED", "Not required"),
                            ("REQUIRED", "Required"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="NOT_ASSESSED",
                        max_length=24,
                    ),
                ),
                ("notification_reference", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "default_permissions": (),
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="ProcessingActivity",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("purpose", models.TextField(max_length=2000)),
                ("data_subject_categories", models.JSONField(default=list)),
                ("personal_data_categories", models.JSONField(default=list)),
                ("authorized_access_summary", models.TextField(max_length=2000)),
                ("safeguards_summary", models.TextField(max_length=2000)),
                ("retention_policy_reference", models.CharField(blank=True, default="", max_length=255)),
                ("policy_basis_reference", models.CharField(blank=True, default="", max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "default_permissions": (),
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="PrivacyReview",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "review_type",
                    models.CharField(
                        choices=[
                            ("PRIVACY_REVIEW", "Privacy review"),
                            ("PIA", "Privacy impact assessment record"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("RESOLVED", "Resolved")],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("scope_summary", models.TextField(max_length=2000)),
                ("findings_summary", models.TextField(blank=True, default="", max_length=4000)),
                ("recommendations_summary", models.TextField(blank=True, default="", max_length=4000)),
                ("resolution_summary", models.TextField(blank=True, default="", max_length=4000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processing_activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="privacy_governance.processingactivity",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="privacy_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "default_permissions": (),
                "ordering": ("-created_at", "-id"),
            },
        ),
    ]
