# Generated by Django 6.1.1 on 2026-09-26 02:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy_governance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyNotice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('code',),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RetentionPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('scope_summary', models.TextField(max_length=2000)),
                ('retention_trigger_summary', models.TextField(max_length=2000)),
                ('retention_period_summary', models.TextField(max_length=1000)),
                ('disposition_summary', models.TextField(max_length=2000)),
                ('policy_reference', models.CharField(blank=True, default='', max_length=255)),
                ('effective_on', models.DateField(blank=True, null=True)),
                ('review_due_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('code',),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='data_subject_choice_summary',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
        migrations.CreateModel(
            name='PrivacyNoticeRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('audiences', models.JSONField(default=list)),
                ('summary', models.TextField(max_length=2000)),
                ('body', models.TextField(max_length=20000)),
                ('requires_acknowledgment', models.BooleanField(default=False)),
                ('effective_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_privacy_notice_revisions', to=settings.AUTH_USER_MODEL)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='privacy_governance.privacynotice')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_privacy_notice_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('notice_id', '-revision_number'),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PrivacyNoticeAcknowledgment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='privacy_notice_acknowledgments', to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acknowledgments', to='privacy_governance.privacynoticerevision')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='retention_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processing_activities', to='privacy_governance.retentionpolicy'),
        ),
        migrations.AddConstraint(
            model_name='privacynoticerevision',
            constraint=models.UniqueConstraint(fields=('notice', 'revision_number'), name='unique_notice_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='privacynoticerevision',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'DRAFT')), fields=('notice',), name='one_notice_draft'),
        ),
        migrations.AddConstraint(
            model_name='privacynoticerevision',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PUBLISHED')), fields=('notice',), name='one_notice_published'),
        ),
        migrations.AddConstraint(
            model_name='privacynoticeacknowledgment',
            constraint=models.UniqueConstraint(fields=('user', 'revision'), name='unique_notice_acknowledgment'),
        ),
    ]
