# Generated by Django for the Privacy Governance scope reduction.

from django.db import migrations, models


LEGACY_MODEL_NAMES = (
    "ProcessingActivity",
    "PrivacyReview",
    "PrivacyIncident",
)


def refuse_destructive_removal_with_legacy_rows(apps, schema_editor):
    """Fail closed before obsolete privacy workflow tables are removed."""

    alias = schema_editor.connection.alias
    populated: list[tuple[str, int]] = []
    for model_name in LEGACY_MODEL_NAMES:
        model = apps.get_model("privacy_governance", model_name)
        count = model.objects.using(alias).count()
        if count:
            populated.append((model_name, count))

    if populated:
        counts = ", ".join(f"{name}={count}" for name, count in populated)
        raise RuntimeError(
            "Privacy Governance scope reduction stopped because legacy records exist "
            f"({counts}). Archive or migrate those records through an explicit "
            "institutional decision before retrying this migration."
        )


class Migration(migrations.Migration):

    dependencies = [
        ("privacy_governance", "0002_privacynotice_retentionpolicy_and_more"),
    ]

    operations = [
        migrations.RunPython(
            refuse_destructive_removal_with_legacy_rows,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name="retentionpolicy",
            name="record_categories",
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name="PrivacyReview",
        ),
        migrations.DeleteModel(
            name="ProcessingActivity",
        ),
        migrations.DeleteModel(
            name="PrivacyIncident",
        ),
    ]
