# Generated by Django 6.1.1 on 2026-10-04 11:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy_governance', '0004_remove_retention_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalRetentionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('GRADUATE_TRACER', 'Graduate Tracer'), ('ECOUNSELING_RECORDING', 'E-Counseling recordings'), ('ECOUNSELING_TRANSCRIPT', 'E-Counseling stored transcripts')], max_length=32)),
                ('trigger', models.CharField(choices=[('SUBMITTED_AT', 'Submission'), ('MEDIA_READY_AT', 'Provider artifact ready')], max_length=24)),
                ('duration_days', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('ANONYMIZE', 'Anonymize'), ('DELETE_PROVIDER_ARTIFACT_KEEP_EVIDENCE', 'Delete provider artifact, keep evidence')], max_length=48)),
                ('policy_reference', models.CharField(max_length=500)),
                ('effective_on', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired')], default='DRAFT', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(null=True)),
                ('retired_at', models.DateTimeField(null=True)),
                ('activated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('retired_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('code',),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='DispositionCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_revision', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('GRADUATE_TRACER', 'Graduate Tracer'), ('ECOUNSELING_RECORDING', 'E-Counseling recordings'), ('ECOUNSELING_TRANSCRIPT', 'E-Counseling stored transcripts')], max_length=32)),
                ('source_id', models.UUIDField()),
                ('source_updated_at', models.DateTimeField()),
                ('eligible_at', models.DateTimeField()),
                ('state', models.CharField(choices=[('READY', 'Needs review'), ('ON_HOLD', 'On hold'), ('BLOCKED', 'Blocked'), ('NO_LONGER_ELIGIBLE', 'No longer eligible'), ('APPROVED', 'Approved'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('RECONCILIATION_REQUIRED', 'Reconciliation required')], default='READY', max_length=32)),
                ('blocker', models.CharField(choices=[('RULE_INACTIVE', 'Rule is inactive or not yet effective'), ('SOURCE_CHANGED', 'Source lifecycle changed'), ('SOURCE_UNAVAILABLE', 'Source is unavailable'), ('MEDIA_NOT_TERMINAL', 'Media lifecycle is unresolved'), ('ARTIFACT_ID_MISSING', 'Provider artifact ID is missing'), ('PROVIDER_UNAVAILABLE', 'Provider unavailable'), ('PROVIDER_REJECTED', 'Provider rejected the request'), ('PROVIDER_UNVERIFIED', 'Provider outcome unverified'), ('EXTERNAL_STORAGE', 'External storage requires operator reconciliation'), ('VERIFICATION_FAILED', 'Disposition verification failed'), ('WORKER_INTERRUPTED', 'Worker interrupted; reconcile before retry')], max_length=32, null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('approved_at', models.DateTimeField(null=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('claim_token', models.UUIDField(null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('manual_retries', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='privacy_governance.operationalretentionrule')),
            ],
            options={
                'ordering': ('eligible_at', 'id'),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='DispositionHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=240)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holds', to='privacy_governance.dispositioncase')),
                ('placed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('case',), name='one_active_disposition_hold')],
            },
        ),
        migrations.AddConstraint(
            model_name='operationalretentionrule',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('category',), name='one_active_retention_category'),
        ),
        migrations.AddConstraint(
            model_name='operationalretentionrule',
            constraint=models.CheckConstraint(condition=models.Q(('duration_days__gte', 1), ('duration_days__lte', 365000)), name='retention_duration_days_valid'),
        ),
        migrations.AddConstraint(
            model_name='operationalretentionrule',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'ACTIVE', 'RETIRED'])), name='retention_rule_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='operationalretentionrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action', 'ANONYMIZE'), ('category', 'GRADUATE_TRACER'), ('trigger', 'SUBMITTED_AT')), models.Q(('action', 'DELETE_PROVIDER_ARTIFACT_KEEP_EVIDENCE'), ('category__in', ('ECOUNSELING_RECORDING', 'ECOUNSELING_TRANSCRIPT')), ('trigger', 'MEDIA_READY_AT')), _connector='OR'), name='retention_supported_treatment'),
        ),
        migrations.AddIndex(
            model_name='dispositioncase',
            index=models.Index(fields=['state', 'next_attempt_at'], name='disposition_dispatch_idx'),
        ),
        migrations.AddConstraint(
            model_name='dispositioncase',
            constraint=models.UniqueConstraint(fields=('category', 'source_id'), name='disposition_source_unique'),
        ),
        migrations.AddConstraint(
            model_name='dispositioncase',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['READY', 'ON_HOLD', 'BLOCKED', 'NO_LONGER_ELIGIBLE', 'APPROVED', 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', 'RECONCILIATION_REQUIRED'])), name='disposition_state_valid'),
        ),
    ]
