# Generated by Django 6.1.1 on 2026-10-07 22:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy_governance', '0005_operationalretentionrule_dispositioncase_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='operationalretentionrule',
            name='one_active_retention_category',
        ),
        migrations.RemoveConstraint(
            model_name='operationalretentionrule',
            name='retention_supported_treatment',
        ),
        migrations.AddField(
            model_name='dispositioncase',
            name='contract_version',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Contract v1'), (2, 'Media policy v2')], default=1),
        ),
        migrations.AddField(
            model_name='operationalretentionrule',
            name='contract_version',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Contract v1'), (2, 'Media policy v2')], default=1),
        ),
        migrations.AlterField(
            model_name='dispositioncase',
            name='blocker',
            field=models.CharField(choices=[('INGESTION_INCOMPLETE', 'File preparation is incomplete'), ('OBJECT_STORAGE_UNAVAILABLE', 'Stored file unavailable'), ('OBJECT_STORAGE_UNVERIFIED', 'Stored file deletion unverified'), ('PROVIDER_CLEANUP_UNVERIFIED', 'Provider cleanup unverified'), ('LOCAL_ARTIFACT_MISSING', 'Stored artifact evidence unavailable'), ('RULE_INACTIVE', 'Rule is inactive or not yet effective'), ('SOURCE_CHANGED', 'Source lifecycle changed'), ('SOURCE_UNAVAILABLE', 'Source is unavailable'), ('MEDIA_NOT_TERMINAL', 'Media lifecycle is unresolved'), ('ARTIFACT_ID_MISSING', 'Provider artifact ID is missing'), ('PROVIDER_UNAVAILABLE', 'Provider unavailable'), ('PROVIDER_REJECTED', 'Provider rejected the request'), ('PROVIDER_UNVERIFIED', 'Provider outcome unverified'), ('EXTERNAL_STORAGE', 'External storage requires operator reconciliation'), ('VERIFICATION_FAILED', 'Disposition verification failed'), ('WORKER_INTERRUPTED', 'Worker interrupted; reconcile before retry')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='operationalretentionrule',
            name='action',
            field=models.CharField(choices=[('DELETE_MEDIA_ARTIFACT_KEEP_EVIDENCE', 'Delete stored media artifact, keep evidence'), ('ANONYMIZE', 'Anonymize'), ('DELETE_PROVIDER_ARTIFACT_KEEP_EVIDENCE', 'Delete provider artifact, keep evidence')], max_length=48),
        ),
        migrations.AddConstraint(
            model_name='operationalretentionrule',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('category', 'contract_version'), name='one_active_retention_contract'),
        ),
        migrations.AddConstraint(
            model_name='operationalretentionrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action', 'ANONYMIZE'), ('category', 'GRADUATE_TRACER'), ('contract_version', 1), ('trigger', 'SUBMITTED_AT')), models.Q(('action', 'DELETE_PROVIDER_ARTIFACT_KEEP_EVIDENCE'), ('category__in', ('ECOUNSELING_RECORDING', 'ECOUNSELING_TRANSCRIPT')), ('contract_version', 1), ('trigger', 'MEDIA_READY_AT')), models.Q(('action', 'DELETE_MEDIA_ARTIFACT_KEEP_EVIDENCE'), ('category__in', ('ECOUNSELING_RECORDING', 'ECOUNSELING_TRANSCRIPT')), ('contract_version', 2), ('trigger', 'MEDIA_READY_AT')), _connector='OR'), name='retention_supported_contract'),
        ),
    ]
