# Generated by Django 6.1.1 on 2026-10-09 12:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0003_service_name_snapshot'),
        ('organization', '0003_program'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidanceThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('OFFICE', 'Guidance Office'), ('COUNSELING', 'Counseling')], max_length=16)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_sequence', models.PositiveBigIntegerField(default=0)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_guidance_threads', to=settings.AUTH_USER_MODEL)),
                ('counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='counselor_guidance_threads', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_guidance_threads', to=settings.AUTH_USER_MODEL)),
                ('relationship_appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guidance_thread', to='appointments.appointment')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_guidance_threads', to=settings.AUTH_USER_MODEL)),
                ('routing_college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.college')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guidance_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_message_at', '-id'),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='GuidanceMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveBigIntegerField()),
                ('client_message_id', models.UUIDField()),
                ('body_ciphertext', models.TextField()),
                ('body_schema_version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_guidance_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='guidance_messages.guidancethread')),
            ],
            options={
                'ordering': ('sequence',),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='GuidanceThreadReadState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_read_sequence', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='read_states', to='guidance_messages.guidancethread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guidance_read_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AddIndex(
            model_name='guidancethread',
            index=models.Index(fields=['routing_college', '-last_message_at', '-id'], name='gm_office_directory_idx'),
        ),
        migrations.AddConstraint(
            model_name='guidancethread',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('counselor__isnull', True), ('kind', 'OFFICE'), ('relationship_appointment__isnull', True), ('routing_college__isnull', False)), models.Q(('assigned_to__isnull', True), ('counselor__isnull', False), ('kind', 'COUNSELING'), ('relationship_appointment__isnull', False), ('routing_college__isnull', True)), _connector='OR'), name='gm_thread_family_shape'),
        ),
        migrations.AddConstraint(
            model_name='guidancethread',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resolved_at__isnull', True), ('resolved_by__isnull', True), ('status', 'OPEN')), models.Q(('resolved_at__isnull', False), ('resolved_by__isnull', False), ('status', 'RESOLVED')), _connector='OR'), name='gm_thread_resolution_shape'),
        ),
        migrations.AddConstraint(
            model_name='guidancethread',
            constraint=models.CheckConstraint(condition=models.Q(('last_sequence__gte', 0)), name='gm_thread_sequence_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='guidancethread',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'OFFICE'), ('status', 'OPEN')), fields=('student',), name='gm_one_open_office_per_student'),
        ),
        migrations.AddConstraint(
            model_name='guidancemessage',
            constraint=models.UniqueConstraint(fields=('thread', 'sequence'), name='gm_message_thread_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='guidancemessage',
            constraint=models.UniqueConstraint(fields=('sender', 'client_message_id'), name='gm_message_sender_client_unique'),
        ),
        migrations.AddConstraint(
            model_name='guidancemessage',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gte', 1)), name='gm_message_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='guidancethreadreadstate',
            constraint=models.UniqueConstraint(fields=('thread', 'user'), name='gm_read_thread_user_unique'),
        ),
        migrations.AddConstraint(
            model_name='guidancethreadreadstate',
            constraint=models.CheckConstraint(condition=models.Q(('last_read_sequence__gte', 0)), name='gm_read_sequence_nonnegative'),
        ),
    ]
