# Generated by Django 6.1.1 on 2026-10-09 23:36

import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.lookups
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidance_messages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidanceMessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archived_guidance_message_templates', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_guidance_message_templates', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_guidance_message_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': (django.db.models.functions.text.Lower('name'), 'id'),
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='gm_template_name_unique_ci'), models.CheckConstraint(condition=models.Q(models.Q(('archived_at__isnull', True), ('archived_by__isnull', True), ('status', 'ACTIVE')), models.Q(('archived_at__isnull', False), ('archived_by__isnull', False), ('status', 'ARCHIVED')), _connector='OR'), name='gm_template_archive_shape'), models.CheckConstraint(condition=models.Q(('name__regex', '^\\s*$'), _negated=True), name='gm_template_name_nonblank'), models.CheckConstraint(condition=models.Q(('body__regex', '^\\s*$'), _negated=True), name='gm_template_body_nonblank'), models.CheckConstraint(condition=django.db.models.lookups.LessThanOrEqual(django.db.models.functions.text.Length('body'), 4000), name='gm_template_body_length')],
            },
        ),
    ]
