# Generated by Django 6.1.1 on 2026-10-05 03:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exit_interviews', '0001_initial'),
        ('organization', '0003_program'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitInterviewOpportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('GRADUATION', 'Graduation'), ('MANUAL', 'Manual')], max_length=16)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('REVOKED', 'Revoked')], default='OPEN', max_length=16)),
                ('opened_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exit_interview_opportunities', to='organization.academicyear')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_exit_interview_opportunities', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_exit_interview_opportunities', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exit_interview_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-opened_at', 'id'),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='exitinterview',
            name='opportunity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exit_interview', to='exit_interviews.exitinterviewopportunity'),
        ),
        migrations.AddIndex(
            model_name='exitinterviewopportunity',
            index=models.Index(fields=['academic_year', 'status'], name='exit_opp_year_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='exitinterviewopportunity',
            constraint=models.UniqueConstraint(fields=('student', 'academic_year'), name='exit_opp_student_year_uniq'),
        ),
        migrations.AddConstraint(
            model_name='exitinterviewopportunity',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ['GRADUATION', 'MANUAL'])), name='exit_opp_source_valid'),
        ),
        migrations.AddConstraint(
            model_name='exitinterviewopportunity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('revoked_at__isnull', True), ('revoked_by__isnull', True), ('status', 'OPEN')), models.Q(('completed_at__isnull', False), ('revoked_at__isnull', True), ('revoked_by__isnull', True), ('status', 'COMPLETED')), models.Q(('completed_at__isnull', True), ('revoked_at__isnull', False), ('revoked_by__isnull', False), ('status', 'REVOKED')), _connector='OR'), name='exit_opp_status_shape'),
        ),
    ]
