# Generated by Django 6.1.1 on 2026-10-04 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduate_tracer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduateTracerDisposedParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_schema_version', models.PositiveSmallIntegerField()),
                ('disposed_on', models.DateField()),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='graduatetracerresponse',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='graduatetracerresponse',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='graduate_tracer_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='graduatetracerresponse',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('anonymized_at__isnull', True), ('student__isnull', False)), models.Q(('anonymized_at__isnull', False), ('status', 'SUBMITTED'), ('student__isnull', True)), _connector='OR'), name='graduate_tracer_identity_shape'),
        ),
        migrations.AddField(
            model_name='graduatetracerdisposedparticipation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='graduatetracerdisposedparticipation',
            constraint=models.UniqueConstraint(fields=('student', 'instrument_schema_version'), name='tracer_disposed_participation_uniq'),
        ),
    ]
