"""Stable audit action codes used by the current COMPASS foundation."""

ACCOUNT_CREATED = "account.created"
ACCOUNT_UPDATED = "account.updated"
ACCOUNT_DISABLED = "account.disabled"
ACCOUNT_ENABLED = "account.enabled"
ACCOUNT_ROLE_CHANGED = "account.role.changed"
ACCOUNT_STUDENT_LIFECYCLE_CHANGED = "account.student_lifecycle.changed"
ACCOUNT_DESIGNATION_ASSIGNED = "account.designation.assigned"
ACCOUNT_DESIGNATION_REMOVED = "account.designation.removed"
ACCOUNT_CAPABILITY_OVERRIDE_SET = "account.capability.override.set"
ACCOUNT_CAPABILITY_OVERRIDE_REMOVED = "account.capability.override.removed"
ACCOUNT_MFA_RESET = "account.mfa.reset"
PROFILE_UPDATED = "profile.updated"
IDENTITY_POLICY_SYNCED = "identity.policy.synced"
ORGANIZATION_CAMPUS_CREATED = "organization.campus.created"
ORGANIZATION_CAMPUS_UPDATED = "organization.campus.updated"
ORGANIZATION_CAMPUS_ENABLED = "organization.campus.enabled"
ORGANIZATION_CAMPUS_DISABLED = "organization.campus.disabled"
ORGANIZATION_COLLEGE_CREATED = "organization.college.created"
ORGANIZATION_COLLEGE_UPDATED = "organization.college.updated"
ORGANIZATION_COLLEGE_ENABLED = "organization.college.enabled"
ORGANIZATION_COLLEGE_DISABLED = "organization.college.disabled"
ORGANIZATION_COUNSELOR_RESPONSIBILITY_ASSIGNED = "organization.counselor_responsibility.assigned"
ORGANIZATION_COUNSELOR_RESPONSIBILITY_CHANGED = "organization.counselor_responsibility.changed"
ORGANIZATION_COUNSELOR_RESPONSIBILITY_REMOVED = "organization.counselor_responsibility.removed"
ORGANIZATION_STAFF_SUPERVISION_ASSIGNED = "organization.staff_supervision.assigned"
ORGANIZATION_STAFF_SUPERVISION_CHANGED = "organization.staff_supervision.changed"
ORGANIZATION_STAFF_SUPERVISION_REMOVED = "organization.staff_supervision.removed"
ORGANIZATION_STUDENT_AFFILIATION_ASSIGNED = "organization.student_affiliation.assigned"
ORGANIZATION_STUDENT_AFFILIATION_CHANGED = "organization.student_affiliation.changed"
ORGANIZATION_STUDENT_AFFILIATION_REMOVED = "organization.student_affiliation.removed"
ACADEMIC_YEAR_CREATED = "academic_year.created"
ACADEMIC_YEAR_CURRENT_CHANGED = "academic_year.current_changed"
INSTITUTIONAL_FORM_REVISION_REGISTERED = "institutional_form.revision_registered"
INSTITUTIONAL_FORM_REVISION_ACTIVATED = "institutional_form.revision_activated"
INSTITUTIONAL_FORM_REVISION_DEACTIVATED = "institutional_form.revision_deactivated"
SERVICE_CREATED = "service.created"
SERVICE_UPDATED = "service.updated"
SERVICE_ENABLED = "service.enabled"
SERVICE_DISABLED = "service.disabled"
AVAILABILITY_OFFICE_SCHEDULE_UPDATED = "availability.office_schedule.updated"
AVAILABILITY_OFFICE_EXCEPTION_CREATED = "availability.office_exception.created"
AVAILABILITY_OFFICE_EXCEPTION_REMOVED = "availability.office_exception.removed"
AVAILABILITY_PROVIDER_SCHEDULE_UPDATED = "availability.provider_schedule.updated"
AVAILABILITY_PROVIDER_EXCEPTION_CREATED = "availability.provider_exception.created"
AVAILABILITY_PROVIDER_EXCEPTION_REMOVED = "availability.provider_exception.removed"
APPOINTMENT_CREATED = "appointment.created"
APPOINTMENT_CANCELLED = "appointment.cancelled"
COUNSELING_ENCOUNTER_CREATED = "counseling.encounter.created"
COUNSELING_ENCOUNTER_UPDATED = "counseling.encounter.updated"
COUNSELING_SHARED_SUMMARY_PUBLISHED = "counseling.shared_summary.published"
INVENTORY_CREATED = "inventory.created"
INVENTORY_SUBMITTED = "inventory.submitted"
GOOD_MORAL_REQUEST_CREATED = "good_moral.request_created"
GOOD_MORAL_REQUEST_UPDATED = "good_moral.request_updated"
GOOD_MORAL_ISSUED = "good_moral.issued"
EXIT_INTERVIEW_CREATED = "exit_interview.created"
EXIT_INTERVIEW_SUBMITTED = "exit_interview.submitted"
EXIT_INTERVIEW_REOPENED = "exit_interview.reopened"
EXIT_INTERVIEW_RESUBMITTED = "exit_interview.resubmitted"
ROUTINE_INTERVIEW_CREATED = "routine_interview.created"
ROUTINE_INTERVIEW_INTAKE_SUBMITTED = "routine_interview.intake_submitted"
ROUTINE_INTERVIEW_EVALUATION_FINALIZED = "routine_interview.evaluation_finalized"
REFERRAL_CREATED = "referral.created"
REFERRAL_ACTION_RECORDED = "referral.action_recorded"
REFERRAL_STATUS_UPDATED = "referral.status_updated"
CALL_SLIP_CREATED = "call_slip.created"
DOCUMENT_BRANDING_UPDATED = "document_branding.updated"
CALL_SLIP_INTERVIEW_ENDED = "call_slip.interview_ended"
ECOUNSELING_ROOM_PROVISIONED = "ecounseling.room_provisioned"
ECOUNSELING_JOIN_AUTHORIZED = "ecounseling.join_authorized"
ECOUNSELING_CONSENT_REQUESTED = "ecounseling.consent_requested"
ECOUNSELING_CONSENT_APPROVED = "ecounseling.consent_approved"
ECOUNSELING_CONSENT_DENIED = "ecounseling.consent_denied"
ECOUNSELING_CONSENT_WITHDRAWN = "ecounseling.consent_withdrawn"
ECOUNSELING_RECORDING_START_REQUESTED = "ecounseling.recording_start_requested"
ECOUNSELING_RECORDING_STOP_REQUESTED = "ecounseling.recording_stop_requested"
ECOUNSELING_TRANSCRIPTION_START_REQUESTED = "ecounseling.transcription_start_requested"
ECOUNSELING_TRANSCRIPTION_STOP_REQUESTED = "ecounseling.transcription_stop_requested"

__all__ = [
    "ACCOUNT_CREATED",
    "ACCOUNT_UPDATED",
    "ACCOUNT_DISABLED",
    "ACCOUNT_ENABLED",
    "ACCOUNT_ROLE_CHANGED",
    "ACCOUNT_STUDENT_LIFECYCLE_CHANGED",
    "ACCOUNT_DESIGNATION_ASSIGNED",
    "ACCOUNT_DESIGNATION_REMOVED",
    "ACCOUNT_CAPABILITY_OVERRIDE_SET",
    "ACCOUNT_CAPABILITY_OVERRIDE_REMOVED",
    "ACCOUNT_MFA_RESET",
    "PROFILE_UPDATED",
    "IDENTITY_POLICY_SYNCED",
    "ORGANIZATION_CAMPUS_CREATED",
    "ORGANIZATION_CAMPUS_UPDATED",
    "ORGANIZATION_CAMPUS_ENABLED",
    "ORGANIZATION_CAMPUS_DISABLED",
    "ORGANIZATION_COLLEGE_CREATED",
    "ORGANIZATION_COLLEGE_UPDATED",
    "ORGANIZATION_COLLEGE_ENABLED",
    "ORGANIZATION_COLLEGE_DISABLED",
    "ORGANIZATION_COUNSELOR_RESPONSIBILITY_ASSIGNED",
    "ORGANIZATION_COUNSELOR_RESPONSIBILITY_CHANGED",
    "ORGANIZATION_COUNSELOR_RESPONSIBILITY_REMOVED",
    "ORGANIZATION_STAFF_SUPERVISION_ASSIGNED",
    "ORGANIZATION_STAFF_SUPERVISION_CHANGED",
    "ORGANIZATION_STAFF_SUPERVISION_REMOVED",
    "ORGANIZATION_STUDENT_AFFILIATION_ASSIGNED",
    "ORGANIZATION_STUDENT_AFFILIATION_CHANGED",
    "ORGANIZATION_STUDENT_AFFILIATION_REMOVED",
    "ACADEMIC_YEAR_CREATED",
    "ACADEMIC_YEAR_CURRENT_CHANGED",
    "INSTITUTIONAL_FORM_REVISION_REGISTERED",
    "INSTITUTIONAL_FORM_REVISION_ACTIVATED",
    "INSTITUTIONAL_FORM_REVISION_DEACTIVATED",
    "SERVICE_CREATED",
    "SERVICE_UPDATED",
    "SERVICE_ENABLED",
    "SERVICE_DISABLED",
    "AVAILABILITY_OFFICE_SCHEDULE_UPDATED",
    "AVAILABILITY_OFFICE_EXCEPTION_CREATED",
    "AVAILABILITY_OFFICE_EXCEPTION_REMOVED",
    "AVAILABILITY_PROVIDER_SCHEDULE_UPDATED",
    "AVAILABILITY_PROVIDER_EXCEPTION_CREATED",
    "AVAILABILITY_PROVIDER_EXCEPTION_REMOVED",
    "APPOINTMENT_CREATED",
    "APPOINTMENT_CANCELLED",
    "COUNSELING_ENCOUNTER_CREATED",
    "COUNSELING_ENCOUNTER_UPDATED",
    "COUNSELING_SHARED_SUMMARY_PUBLISHED",
    "INVENTORY_CREATED",
    "INVENTORY_SUBMITTED",
    "GOOD_MORAL_REQUEST_CREATED",
    "GOOD_MORAL_REQUEST_UPDATED",
    "GOOD_MORAL_ISSUED",
    "EXIT_INTERVIEW_CREATED",
    "EXIT_INTERVIEW_SUBMITTED",
    "EXIT_INTERVIEW_REOPENED",
    "EXIT_INTERVIEW_RESUBMITTED",
    "ROUTINE_INTERVIEW_CREATED",
    "ROUTINE_INTERVIEW_INTAKE_SUBMITTED",
    "ROUTINE_INTERVIEW_EVALUATION_FINALIZED",
    "REFERRAL_CREATED",
    "REFERRAL_ACTION_RECORDED",
    "REFERRAL_STATUS_UPDATED",
    "CALL_SLIP_CREATED",
    "DOCUMENT_BRANDING_UPDATED",
    "CALL_SLIP_INTERVIEW_ENDED",
    "ECOUNSELING_ROOM_PROVISIONED",
    "ECOUNSELING_JOIN_AUTHORIZED",
    "ECOUNSELING_CONSENT_REQUESTED",
    "ECOUNSELING_CONSENT_APPROVED",
    "ECOUNSELING_CONSENT_DENIED",
    "ECOUNSELING_CONSENT_WITHDRAWN",
    "ECOUNSELING_RECORDING_START_REQUESTED",
    "ECOUNSELING_RECORDING_STOP_REQUESTED",
    "ECOUNSELING_TRANSCRIPTION_START_REQUESTED",
    "ECOUNSELING_TRANSCRIPTION_STOP_REQUESTED",
]
