# Generated by Django 6.1.1 on 2026-10-05 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exit_interviews', '0002_exitinterviewopportunity_exitinterview_opportunity_and_more'),
        ('good_moral', '0003_request_creation_identity'),
        ('institutional_forms', '0007_customer_feedback_family'),
        ('inventory', '0005_submission_history_reopen'),
        ('organization', '0003_program'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goodmoralrequest',
            name='exit_interview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='good_moral_requests', to='exit_interviews.exitinterview'),
        ),
        migrations.AddField(
            model_name='goodmoralrequest',
            name='exit_interview_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goodmoralrequest',
            name='graduation_opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='good_moral_requests', to='exit_interviews.exitinterviewopportunity'),
        ),
        migrations.AddConstraint(
            model_name='goodmoralrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('exit_interview__isnull', True), ('exit_interview_submitted_at__isnull', True), ('graduation_opportunity__isnull', True)), models.Q(('exit_interview__isnull', False), ('exit_interview_submitted_at__isnull', False), ('graduation_opportunity__isnull', False), ('variant', 'CURRENT_STUDENT')), _connector='OR'), name='good_moral_exit_prereq_shape'),
        ),
    ]
