# Generated by Django 6.1.1 on 2026-10-05 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_moral', '0003_request_creation_identity'),
        ('institutional_forms', '0007_customer_feedback_family'),
        ('inventory', '0005_submission_history_reopen'),
        ('organization', '0003_program'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='goodmoralrequest',
            name='good_moral_issuance_shape',
        ),
        migrations.RemoveConstraint(
            model_name='goodmoralrequest',
            name='good_moral_cancellation_shape',
        ),
        migrations.AddField(
            model_name='goodmoralrequest',
            name='prepared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goodmoralrequest',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prepared_good_moral_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='goodmoralrequest',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('READY_FOR_ISSUANCE', 'Ready for issuance'), ('ISSUED', 'Issued'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=24),
        ),
        migrations.AddConstraint(
            model_name='goodmoralrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('prepared_at__isnull', True), ('prepared_by__isnull', True), models.Q(('status', 'READY_FOR_ISSUANCE'), _negated=True)), models.Q(('prepared_at__isnull', False), ('prepared_by__isnull', False), ('status__in', ('READY_FOR_ISSUANCE', 'ISSUED', 'CANCELLED'))), _connector='OR'), name='good_moral_preparation_shape'),
        ),
        migrations.AddConstraint(
            model_name='goodmoralrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('document_template_key__isnull', True), ('document_template_version__isnull', True), ('form_revision__isnull', True), ('issued_at__isnull', True), ('issued_by__isnull', True), ('issued_by_name_snapshot', ''), ('status__in', ('REQUESTED', 'READY_FOR_ISSUANCE', 'CANCELLED'))), models.Q(('document_template_key__isnull', False), ('document_template_version__isnull', False), ('form_revision__isnull', False), ('issued_at__isnull', False), ('issued_by__isnull', False), ('status', 'ISSUED'), models.Q(('issued_by_name_snapshot', ''), _negated=True)), _connector='OR'), name='good_moral_issuance_shape'),
        ),
        migrations.AddConstraint(
            model_name='goodmoralrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancellation_reason', ''), ('cancelled_at__isnull', True), ('status__in', ('REQUESTED', 'READY_FOR_ISSUANCE', 'ISSUED'))), models.Q(('cancelled_at__isnull', False), ('status', 'CANCELLED'), models.Q(('cancellation_reason', ''), _negated=True)), _connector='OR'), name='good_moral_cancellation_shape'),
        ),
    ]
