# Generated by Django 6.1.1 on 2026-10-05 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('good_moral', '0004_goodmoralrequest_exit_interview_and_more'),
        ('good_moral', '0004_remove_goodmoralrequest_good_moral_issuance_shape_and_more'),
    ]

    operations = [
    ]
